const blogPosts = [
  {
    id: 1,
    title: "Top Reasons Why Professional Logo Design in Dubai",
    date: "Dec 10, 2025",
    author: "Admin",
    image: "/assets/blog/blog-1/Logo Design in Dubai.jpg",
    categories: ["branding", "web-design"],
    effect: "reveal zoom-out",
    slug:"top-reasons-why-professional-logo-design-in-dubai",
  },
  {
    id: 2,
    title: "Why Startups Prefer Working with a Freelance Graphic Designer Dubai",
    date: "Dec 08, 2025",
    author: "Admin",
    image: "/assets/blog/blog-2/Why Startups Prefer Working with a Freelance Graphic Designer Dubai.jpg",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"why-startups-prefer-working-with-a-freelance-graphic-designer-dubai",

  },
  {
    id: 3,
    title: "How to Choose a Freelance Graphic Designer in Dubai?",
    date: "Dec 24, 2025",
    author: "Admin",
    image: "/assets/blog/blog-3/Freelance Graphic Designer.bmp",
    categories: ["video", "web-design", "marketing"],
    effect: "reveal left",
    slug:"how-to-choose-a-freelance-graphic-designer-in-dubai",

  },
  {
    id: 4,
    title: "What Does a Freelance Graphic Designer in Dubai Do?",
    date: "Dec 24, 2025",
    author: "Admin",
    image: "/assets/blog/blog-4/What Does a Freelance Graphic Designer in Dubai.jpg",
    categories: ["branding", "marketing", "video"],
    effect: "reveal right",
    slug:"what-does-a-freelance-graphic-designer-in-dubai-do",

  },
  {
    id: 5,
    title: "What Is Professional Logo Design and Why Is It Important?",
    date: "Dec 30, 2024",
    author: "Admin",
    image: "/assets/blog/blog-5/What Is Professional Logo Design and Why Is It Important.jpg",
    categories: ["marketing", "branding"],
    effect: "reveal left",
    slug:"what-is-professional-logo-design-and-why-is-it-important",

  },
  {
    id: 6,
    title: "Why Do Businesses in Dubai Need Branding",
    date: "Dec 30, 2025",
    author: "Admin",
    image: "/assets/blog/blog-6/Why Do Businesses in Dubai Need Branding.jpg",
    categories: ["branding", "web-design"],
    effect: "reveal zoom-out",
    slug:"why-do-businesses-in-dubai-need-branding",
  },
  {
    id: 7,
    title: "Do I Need a Logo Before Starting a Business in Dubai?",
    date: "Dec 08, 2025",
    author: "Admin",
    image: "/assets/blog/blog-7/Do I Need a Logo Before Starting a Business in Dubai.jpg",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"do-i-need-a-logo-before-starting-a-business-in-dubai",

  },  
  {
    id: 8,
    title: "Startup Branding Guide for Dubai Businesses",
    date: "Dec 08, 2025",
    author: "Admin",
    image: "/assets/blog/blog-8/Startup Branding Guide for Dubai Businesses.jpg",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"startup-branding-guide-for-dubai-businesses",

  },
  {
    id: 9,
    title: "How Graphic Design Helps Business Growth in Dubai",
    date: "Jan 12, 2026",
    author: "Admin",
    image: "/assets/blog/blog-9/How Graphic Design Helps Business Growth in Dubai.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"how-graphic-design-helps-business-growth-in-dubai",
  },
  {
    id: 10,
    title: "How Professional Design Helps Businesses Stand Out in Dubai",
    date: "Jan 13, 2026",
    author: "Admin",
    image: "/assets/blog/blog-10/How Professional Design Helps Businesses Stand Out in Dubai.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"how-professional-design-helps-businesses-stand-out-in-dubai",
  },
  {
    id: 11,
    title: "Graphic Design Trends in Dubai for 2026",
    date: "Jan 15, 2026",
    author: "Admin",
    image: "/assets/blog/blog-11/Graphic Design Trends in Dubai for 2026.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"graphic-design-trends-in-dubai-2026",
  },
  {
    id: 12,
    title: "What Services Does a Freelance Graphic Designer Offer?",
    date: "Jan 29, 2026",
    author: "Admin",
    image: "/assets/blog/blog-13/What Services Does a Freelance Graphic Designer Offer.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"what-services-does-a-freelance-graphic-designer-offer",
  },
  {
    id: 13,
    title: "How to Know if Your Logo Needs a Redesign",
    date: "Jan 30, 2026",
    author: "Admin",
    image: "/assets/blog/blog-14/How to Know if Your Logo Needs a Redesign.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"how-to-know-if-your-logo-needs-a-redesign",
  },
  {
    id: 14,
    title: "How Does a Freelance Graphic Designer Work with Clients in Dubai",
    date: "Feb 05, 2026",
    author: "Admin",
    image: "/assets/blog/blog-15/How Does a Freelance Graphic Designer Work with Clients in Dubai.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"how-does-a-freelance-graphic-designer-work-with-clients-in-dubai",

  },
  {
    id: 15,
    title: "Top 10 Freelance Graphic Designers in Dubai 2026",
    date: "Feb 08, 2026",
    author: "Admin",
    image: "/assets/blog/blog-16/Top 10 Freelance Graphic Designers in Dubai 2026.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal left",
    slug:"top-10-freelance-graphic-designers-in-dubai-2026",

  },
  {
    id: 17,
    title: "Bilingual and Arabic Design Significance in Dubai",
    date: "Feb 14, 2026",
    author: "Admin",
    image: "/assets/blog/blog-17/Bilingual and Arabic Design Significance in Dubai.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal left",
    slug:"bilingual-and-arabic-design-significance-in-dubai",

  },
  {
    id: 18,
    title: "Types of Logos Explained: Which One Is Right for Your Business?",
    date: "Feb 18, 2026",
    author: "Admin",
    image: "/assets/blog/blog-18/Which One Is Right for Your Businesss.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal left",
    slug:"types-of-logos-explained-which-one-is-right-for-your-business",

  },
  {
    id: 19,
    title: "How Logo and Graphic Design Work Together in Branding",
    date: "Mar 01, 2026",
    author: "Admin",
    image: "/assets/blog/blog-19/How Logo and Graphic Design Work Together in Branding.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"how-logo-and-graphic-design-work-together-in-branding",

  },
  {
    id: 20,
    title: "UX Design Trends Businesses Should Follow in 2026",
    date: "Mar 05, 2026",
    author: "Admin",
    image: "/assets/blog/blog-20/UX Design Trends Businesses Should Follow in 2026.png",
    categories: ["video", "web-design", "branding"],
    effect: "reveal right",
    slug:"ux-design-trends-businesses-should-follow-2026",

  },

];

export default blogPosts;
