export const workExperienceData1 = [
    {
      date: "2021-2024",
      alt: "adobe",
      src: "/mistersaadassets/icons/adobe.svg",
      width: 240,
      height: 213,
      title: "Adobe",
      subtitle: "Senior UI UX Designer",
    },
    {
      date: "2021-2024",
      alt: "google",
      src: "/mistersaadassets/icons/google.svg",
      width: 24,
      height: 24,
      title: "Google Inc.",
      subtitle: "Senior Designer",
    },
    {
      date: "2021-2024",
      alt: "meta",
      src: "/mistersaadassets/icons/meta.svg",
      width: 48,
      height: 48,
      title: "Meta Inc.",
      subtitle: "Product Designer",
    },
    {
      date: "2021-2024",
      alt: "adobe",
      src: "/mistersaadassets/icons/adobe.svg",
      width: 240,
      height: 213,
      title: "Adobe",
      subtitle: "Senior UI UX Designer",
    },
  ];
  
  export const workExperienceData2 = [
    {
      date: "2021-2024",
      alt: "adobe",
      src: "/mistersaadassets/icons/adobe.svg",
      width: 240,
      height: 213,
      title: "Adobe",
      subtitle: "Senior UI UX Designer",
    },
    {
      date: "2021-2024",
      alt: "google",
      src: "/mistersaadassets/icons/google.svg",
      width: 24,
      height: 24,
      title: "Google Inc.",
      subtitle: "Senior Designer",
    },
    {
      date: "2021-2024",
      alt: "meta",
      src: "/mistersaadassets/icons/meta.svg",
      width: 48,
      height: 48,
      title: "Meta Inc.",
      subtitle: "Product Designer",
    },
    {
      date: "2021-2024",
      alt: "adobe",
      src: "/mistersaadassets/icons/adobe.svg",
      width: 240,
      height: 213,
      title: "Adobe",
      subtitle: "Senior UI UX Designer",
    },
  ];