const portfolioData = [
  {
    id: 1,
    title: "Responsive Website Design",
    image: "./assets/images/portfolio-area/portfolio-extend-1.png",
    tags: ["UI DESIGN", "UX DESIGN", "CREATIVE"],
    link: "/portfolio-details",
    className: "custom-left",
    animation: "reveal left",
  },
  {
    id: 2,
    title: "Mobile Apps Design",
    image: "./assets/images/portfolio-area/portfolio-extend-2.png",
    tags: ["UI DESIGN", "UX DESIGN", "CREATIVE"],
    link: "/portfolio-details",
    className: "custom-left",
    animation: "reveal right",
  },
  {
    id: 3,
    title: "Digital Brand Guidelines",
    image: "./assets/images/portfolio-area/portfolio-extend-3.png",
    tags: ["UI DESIGN", "UX DESIGN", "CREATIVE"],
    link: "/portfolio-details",
    className: "custom-left",
    animation: "reveal right",
  },
  {
    id: 4,
    title: "E-commerce Platform",
    image: "./assets/images/portfolio-area/portfolio-extend-4.png",
    tags: ["UI DESIGN", "UX DESIGN", "CREATIVE"],
    link: "/portfolio-details",
    className: "custom-right",
    animation: "reveal left",
  },
  {
    id: 5,
    title: "Productivity Dashboard",
    image: "./assets/images/portfolio-area/portfolio-extend-5.png",
    tags: ["UI DESIGN", "UX DESIGN", "CREATIVE"],
    link: "/portfolio-details",
    className: "custom-left",
    animation: "reveal left",
  },
  {
    id: 6,
    title: "Mobile Banking App",
    image: "./assets/images/portfolio-area/portfolio-extend-6.png",
    tags: ["UI DESIGN", "UX DESIGN", "CREATIVE"],
    link: "/portfolio-details",
    className: "custom-right",
    animation: "reveal right",
  },
];

export default portfolioData;
